name: tests

on:
  push:
    branches:
      - master  # 指定要触发工作流的分支为 master
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'  # 设置 JDK 版本为 21，与你的 pom.xml 一致

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn -B test  # 这里假设 pom.xml 在根目录
